/**
 * Low-resolution previews of the showcase images, keyed by the original path.
 *
 * Generated by `scripts/build-image-variants.mjs` — do not edit by hand.
 *
 * Portfolio card / hero covers are intentionally absent: main serves full PNG
 * so scaled cards stay sharp (soft q40 WebP twins are not used for those).
 */
export const LOW_RES_IMAGES = Object.freeze({
  "images/comp.png": "images/lq/comp.webp",
  "images/img-3.png": "images/lq/img-3.webp",
  "images/img-bg.png": "images/lq/img-bg.webp"
});
