/**
 * Low-resolution twins of the showcase images, keyed by the original path.
 *
 * Generated by `scripts/build-image-variants.mjs` — do not edit by hand.
 */
export const LOW_RES_IMAGES = Object.freeze({
  "images/card-citybike.png": "images/lq/card-citybike.png",
  "images/card-default.png": "images/lq/card-default.jpg",
  "images/card-innodragon.png": "images/lq/card-innodragon.png",
  "images/card-innophish.png": "images/lq/card-innophish.png",
  "images/case-dragon-hero.png": "images/lq/case-dragon-hero.png",
  "images/comp.png": "images/lq/comp.png",
  "images/dragon.png": "images/lq/dragon.png",
  "images/img-1.png": "images/lq/img-1.png",
  "images/img-2.png": "images/lq/img-2.png",
  "images/img-3.png": "images/lq/img-3.jpg",
  "images/macbook-248-17115.png": "images/lq/macbook-248-17115.jpg",
  "images/macbook-lid.png": "images/lq/macbook-lid.jpg",
  "images/macbook.png": "images/lq/macbook.jpg",
  "images/me.png": "images/lq/me.png",
  "images/phish.png": "images/lq/phish.png",
  "images/stickers/seal.png": "images/lq/stickers/seal.png",
  "images/stickers/sport.png": "images/lq/stickers/sport.png"
});
